name: "Publish Release"

on:
  workflow_dispatch

# Allow one run of this workflow per branch and cancel existing runs if triggered again
concurrency:
  group: snoobrowser-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0' # Load entire history
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      - run: dotnet tool restore
      - name: Generate Version
        id: generate-version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          dotnet tool run versionize
          cd ./SnooBrowser/
          echo "RELEASE_VERSION_NUMBER=$(dotnet tool run versionize inspect)" >> $GITHUB_OUTPUT
          git push --follow-tags
          git fetch --tags origin
      - run: dotnet restore
      - run: dotnet build --no-restore -c Release -p:Version=${{ steps.generate-version.RELEASE_VERSION_NUMBER }}
      - run: dotnet pack --no-build --no-restore --nologo --output=dist -c Release
      - run: gh release create "v${{ steps.generate-version.RELEASE_VERSION_NUMBER }}" --notes-file CHANGELOG.md "dist/SnooBrowser.${{ steps.generate-version.RELEASE_VERSION_NUMBER }}.nupkg" "dist/SnooBrowser.Extensions.DependencyInjection.${{ steps.generate-version.RELEASE_VERSION_NUMBER }}.nupkg"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Publish to NuGet
        run: dotnet nuget push "./dist/*.nupkg" --api-key=${{ secrets.NUGET_API_KEY }}
